package hardware;

public enum ErrorStatus {
	NONE,
	HALT_INSTRUCTION,
	STOP,
	INVALID_OPCODE,
	INVALID_MEMORY_ACCESS,
	INVALID_CONDITION_CODE,
	ARITHMETIC_UNIT_ERROR,
	WORKING_REGISTER_SET_ERROR

}// ErrorType
